// eb-mdt/eb-mdt/web/src/components/VehiclesPage.tsx
import React, { useState, useEffect, useCallback } from "react";
import { fetchNui } from "../utils/fetchNui";
import { classNames } from "../utils/misc";

// Types (keeping the same as original)
interface Vehicle {
  id: number;
  plate: string;
  model: string;
  owner: string;
  citizenid: string;
  state: number;
  inGarage: boolean;
  isJobVehicle: boolean;
  isGangVehicle: boolean;
  flags?: VehicleFlag[];
}

interface VehicleFlag {
  id: number;
  vehicle_id: number;
  flag_type: string;
  description: string;
  reported_by: string;
  created_at: string;
  is_active?: boolean;
  priority?: string;
}

interface DetailedVehicle extends Vehicle {
  fakePlate?: string;
  modelHash: string;
  ownerPhone: string;
  ownerBirthdate: string;
  ownerGender: string;
  garage: string;
  fuel: number;
  engine: number;
  body: number;
  depotPrice: number;
  drivingDistance: number;
  status: string;
  jobVehicleRank: number;
  gangVehicleRank: number;
  mods: Record<string, any>;
  damage: Record<string, any>;
  glovebox: any[];
  trunk: any[];
  flags: VehicleFlag[];
}

interface VehiclesPageProps {
  onViewProfile?: (citizenid: string) => void;
  navigationData?: any;
}

const VehiclesPage: React.FC<VehiclesPageProps> = ({
  onViewProfile,
  navigationData,
}) => {
  // View state - either 'list' or 'detail'
  const [viewMode, setViewMode] = useState<"list" | "detail">("list");

  const [searchQuery, setSearchQuery] = useState("");
  const [vehicles, setVehicles] = useState<Vehicle[]>([]);
  const [selectedVehicle, setSelectedVehicle] =
    useState<DetailedVehicle | null>(null);
  const [loading, setLoading] = useState(false);
  const [vehicleLoading, setVehicleLoading] = useState(false);
  const [hasSearched, setHasSearched] = useState(false);

  // BOLO Management State
  const [boloModalOpen, setBoloModalOpen] = useState(false);
  const [editingFlag, setEditingFlag] = useState<VehicleFlag | null>(null);
  const [boloForm, setBoloForm] = useState({
    flagType: "bolo",
    description: "",
    priority: "medium",
  });

  // Handle navigation data for plate search from dashboard
  useEffect(() => {
    if (navigationData && navigationData.searchQuery) {
      setSearchQuery(navigationData.searchQuery);
      handleSearchWithQuery(navigationData.searchQuery);
    }
  }, [navigationData]);

  const handleSearchWithQuery = async (query: string) => {
    if (!query.trim()) {
      setVehicles([]);
      setHasSearched(false);
      return;
    }

    setLoading(true);
    setHasSearched(true);
    try {
      const results = await fetchNui<Vehicle[]>("searchVehicles", {
        query: query,
      });
      setVehicles(results || []);
    } catch (error) {
      console.error("Error searching vehicles:", error);
      setVehicles([]);
    } finally {
      setLoading(false);
    }
  };

  const handleSearch = async () => {
    if (!searchQuery.trim()) {
      setVehicles([]);
      setHasSearched(false);
      return;
    }

    setLoading(true);
    setHasSearched(true);
    try {
      const results = await fetchNui<Vehicle[]>("searchVehicles", {
        query: searchQuery,
      });
      setVehicles(results || []);
    } catch (error) {
      console.error("Error searching vehicles:", error);
      setVehicles([]);
    } finally {
      setLoading(false);
    }
  };

  const viewVehicle = async (vehicleId: number) => {
    setVehicleLoading(true);
    setViewMode("detail");
    try {
      const vehicle = await fetchNui<DetailedVehicle>("getVehicle", {
        vehicleId,
      });
      if (vehicle) {
        setSelectedVehicle(vehicle);
      }
    } catch (error) {
      console.error("Error loading vehicle:", error);
    } finally {
      setVehicleLoading(false);
    }
  };

  const handleViewProfile = (citizenid: string) => {
    if (onViewProfile) {
      onViewProfile(citizenid);
    }
  };

  const handleBackToList = useCallback(() => {
    setViewMode("list");
    setSelectedVehicle(null);
  }, []);

  const getVehicleStatus = (vehicle: DetailedVehicle | Vehicle) => {
    if (vehicle.flags && vehicle.flags.length > 0) {
      const stolenFlag = vehicle.flags.find(
        (f) => f.flag_type === "stolen" && f.is_active !== false
      );
      if (stolenFlag) return { text: "STOLEN", color: "bg-red-500" };

      const warrantFlag = vehicle.flags.find(
        (f) => f.flag_type === "warrant" && f.is_active !== false
      );
      if (warrantFlag) return { text: "WARRANT", color: "bg-orange-500" };

      const boloFlag = vehicle.flags.find(
        (f) =>
          (f.flag_type === "bolo" || f.flag_type === "wanted") &&
          f.is_active !== false
      );
      if (boloFlag) return { text: "BOLO", color: "bg-yellow-500" };

      const suspiciousFlag = vehicle.flags.find(
        (f) => f.flag_type === "suspicious" && f.is_active !== false
      );
      if (suspiciousFlag) return { text: "SUSPICIOUS", color: "bg-blue-500" };
    }

    return { text: "CLEAN", color: "bg-green-500" };
  };

  const getFlagColor = (flagType: string) => {
    switch (flagType) {
      case "stolen":
        return "#ef4444";
      case "warrant":
        return "#f97316";
      case "bolo":
      case "wanted":
        return "#eab308";
      case "suspicious":
        return "#3b82f6";
      default:
        return "#6b7280";
    }
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString();
  };

  // BOLO Management Functions
  const openBoloModal = (flag?: VehicleFlag) => {
    if (flag) {
      setEditingFlag(flag);
      setBoloForm({
        flagType: flag.flag_type,
        description: flag.description,
        priority: flag.priority || "medium",
      });
    } else {
      setEditingFlag(null);
      setBoloForm({
        flagType: "bolo",
        description: "",
        priority: "medium",
      });
    }
    setBoloModalOpen(true);
  };

  const closeBoloModal = () => {
    setBoloModalOpen(false);
    setEditingFlag(null);
    setBoloForm({
      flagType: "bolo",
      description: "",
      priority: "medium",
    });
  };

  const handleBoloSubmit = async () => {
    if (!selectedVehicle || !boloForm.description.trim()) return;

    try {
      if (editingFlag) {
        await fetchNui("updateVehicleBolo", {
          vehicleId: selectedVehicle.id,
          flagId: editingFlag.id,
          description: boloForm.description,
          priority: boloForm.priority,
        });
      } else {
        await fetchNui("addVehicleBolo", {
          vehicleId: selectedVehicle.id,
          flagType: boloForm.flagType,
          description: boloForm.description,
          priority: boloForm.priority,
        });
      }

      await viewVehicle(selectedVehicle.id);
      closeBoloModal();
    } catch (error) {
      console.error("Error managing BOLO:", error);
    }
  };

  const handleRemoveFlag = async (flag: VehicleFlag) => {
    if (!selectedVehicle) return;

    try {
      await fetchNui("removeVehicleBolo", {
        vehicleId: selectedVehicle.id,
        flagId: flag.id,
        reason: "Removed via MDT",
      });

      await viewVehicle(selectedVehicle.id);
    } catch (error) {
      console.error("Error removing flag:", error);
    }
  };

  if (viewMode === "detail") {
    return (
      <div className="h-full flex flex-col">
        {/* Header */}
        <div className="mdt-card p-4 mb-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <button
                className="w-10 h-10 rounded-lg bg-mdt-accent hover:bg-gray-600 flex items-center justify-center transition-colors"
                onClick={handleBackToList}
              >
                <i className="fas fa-chevron-left text-white"></i>
              </button>
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-primary-600 rounded-lg flex items-center justify-center text-white">
                  <i className="fas fa-car"></i>
                </div>
                <div>
                  <h2 className="text-lg font-semibold text-white">
                    Vehicle Details
                  </h2>
                  <p className="text-sm text-primary-200">
                    {selectedVehicle?.plate || "Unknown"}
                  </p>
                </div>
              </div>
            </div>
            <button
              className="mdt-button mdt-button-primary flex items-center gap-2"
              onClick={() => openBoloModal()}
            >
              <i className="fas fa-flag"></i>
              Add BOLO
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="mdt-card flex-1 overflow-hidden">
          {vehicleLoading ? (
            <div className="flex items-center justify-center h-80">
              <div className="loading-spinner"></div>
            </div>
          ) : selectedVehicle ? (
            <div className="p-6 h-full overflow-auto custom-scrollbar space-y-6">
              {/* Vehicle Status Alert */}
              {(() => {
                const status = getVehicleStatus(selectedVehicle);
                return (
                  <div
                    className="p-4 rounded-lg border-l-4"
                    style={{
                      borderLeftColor:
                        status.color.replace("bg-", "") === "red-500"
                          ? "#ef4444"
                          : status.color.replace("bg-", "") === "orange-500"
                          ? "#f97316"
                          : status.color.replace("bg-", "") === "yellow-500"
                          ? "#eab308"
                          : status.color.replace("bg-", "") === "blue-500"
                          ? "#3b82f6"
                          : "#22c55e",
                      backgroundColor: "rgba(55, 65, 81, 0.5)",
                    }}
                  >
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-semibold text-white">
                        BOLO Status:
                      </span>
                      <span
                        className={classNames("badge text-white", status.color)}
                      >
                        {status.text}
                      </span>
                    </div>
                  </div>
                );
              })()}

              {/* Basic Vehicle Info */}
              <div className="profile-section">
                <h4>Vehicle Details</h4>
                <div className="space-y-3">
                  <div className="profile-row">
                    <span className="profile-label">License Plate</span>
                    <span className="badge badge-outline">
                      {selectedVehicle.plate}
                    </span>
                  </div>
                  {selectedVehicle.fakePlate && (
                    <div className="profile-row">
                      <span className="profile-label">Fake Plate</span>
                      <span className="badge bg-red-500 text-white">
                        {selectedVehicle.fakePlate}
                      </span>
                    </div>
                  )}
                  <div className="profile-row">
                    <span className="profile-label">Model</span>
                    <span className="profile-value">
                      {selectedVehicle.model}
                    </span>
                  </div>
                  <div className="profile-row">
                    <span className="profile-label">Vehicle Type</span>
                    <div className="flex gap-2">
                      {selectedVehicle.isJobVehicle && (
                        <span className="badge bg-blue-500 text-white text-xs">
                          Job Vehicle
                        </span>
                      )}
                      {selectedVehicle.isGangVehicle && (
                        <span className="badge bg-purple-500 text-white text-xs">
                          Gang Vehicle
                        </span>
                      )}
                      {!selectedVehicle.isJobVehicle &&
                        !selectedVehicle.isGangVehicle && (
                          <span className="badge bg-gray-500 text-white text-xs">
                            Personal
                          </span>
                        )}
                    </div>
                  </div>
                </div>
              </div>

              {/* Owner Info */}
              <div className="profile-section">
                <h4>Registered Owner</h4>
                <div className="space-y-3">
                  <div className="profile-row">
                    <span className="profile-label flex items-center gap-2">
                      <i className="fas fa-user info-icon"></i>
                      Name
                    </span>
                    <button
                      className="text-sm font-medium text-primary-400 hover:text-primary-300 transition-colors"
                      onClick={() =>
                        handleViewProfile(selectedVehicle.citizenid)
                      }
                    >
                      {selectedVehicle.owner}
                    </button>
                  </div>
                  <div className="profile-row">
                    <span className="profile-label flex items-center gap-2">
                      <i className="fas fa-phone info-icon"></i>
                      Phone
                    </span>
                    <span className="profile-value">
                      {selectedVehicle.ownerPhone}
                    </span>
                  </div>
                  <div className="profile-row">
                    <span className="profile-label flex items-center gap-2">
                      <i className="fas fa-id-card info-icon"></i>
                      Citizen ID
                    </span>
                    <span className="profile-value font-mono">
                      {selectedVehicle.citizenid}
                    </span>
                  </div>
                </div>
              </div>

              {/* Active Flags */}
              <div className="profile-section">
                <div className="flex items-center justify-between mb-3">
                  <h4 className="text-sm font-medium flex items-center gap-2 text-red-400">
                    <i className="fas fa-exclamation-triangle"></i>
                    Active Flags (
                    {selectedVehicle.flags?.filter((f) => f.is_active !== false)
                      .length || 0}
                    )
                  </h4>
                  <button
                    className="mdt-button mdt-button-primary text-xs py-1 px-3 flex items-center gap-2"
                    onClick={() => openBoloModal()}
                  >
                    <i className="fas fa-plus"></i>
                    Add Flag
                  </button>
                </div>

                {selectedVehicle.flags &&
                selectedVehicle.flags.filter((f) => f.is_active !== false)
                  .length > 0 ? (
                  <div className="space-y-3">
                    {selectedVehicle.flags
                      .filter((f) => f.is_active !== false)
                      .map((flag) => (
                        <div
                          key={flag.id}
                          className="p-3 rounded-lg border-l-4 bg-mdt-bg"
                          style={{
                            borderLeftColor: getFlagColor(flag.flag_type),
                          }}
                        >
                          <div className="flex items-center justify-between mb-2">
                            <div className="flex items-center gap-2">
                              <span
                                className="badge text-white text-xs"
                                style={{
                                  backgroundColor: getFlagColor(flag.flag_type),
                                }}
                              >
                                {flag.flag_type.toUpperCase()}
                              </span>
                              {flag.priority && (
                                <span
                                  className={classNames(
                                    "badge text-white text-xs",
                                    flag.priority === "critical"
                                      ? "bg-red-500"
                                      : flag.priority === "high"
                                      ? "bg-orange-500"
                                      : "bg-gray-500"
                                  )}
                                >
                                  {flag.priority.toUpperCase()}
                                </span>
                              )}
                            </div>
                            <div className="flex items-center gap-2">
                              <span className="text-xs text-primary-200">
                                {formatDate(flag.created_at)}
                              </span>
                              <button
                                className="w-6 h-6 text-primary-200 hover:text-white transition-colors"
                                onClick={() => {
                                  if (confirm("Remove this flag?")) {
                                    handleRemoveFlag(flag);
                                  }
                                }}
                              >
                                <i className="fas fa-times"></i>
                              </button>
                            </div>
                          </div>
                          {flag.description && (
                            <p className="text-xs text-primary-200 mb-2">
                              {flag.description}
                            </p>
                          )}
                          <p className="text-xs text-primary-200">
                            Reported by: {flag.reported_by}
                          </p>
                        </div>
                      ))}
                  </div>
                ) : (
                  <div className="text-center py-8">
                    <span className="text-primary-200 text-sm">
                      No active flags on this vehicle
                    </span>
                  </div>
                )}
              </div>
            </div>
          ) : (
            <div className="flex items-center justify-center h-80">
              <span className="text-primary-200">Vehicle not found</span>
            </div>
          )}
        </div>

        {/* BOLO Management Modal */}
        {boloModalOpen && (
          <div className="modal-overlay">
            <div className="modal-container max-w-md">
              <div className="modal-header">
                <h2 className="text-lg font-semibold text-white">
                  {editingFlag ? "Edit Vehicle Flag" : "Add Vehicle Flag"}
                </h2>
              </div>

              <div className="modal-content space-y-4">
                <div>
                  <label className="block text-sm font-medium mb-2 text-white">
                    Flag Type
                  </label>
                  <select
                    className="mdt-input w-full"
                    value={boloForm.flagType}
                    onChange={(e) =>
                      setBoloForm({ ...boloForm, flagType: e.target.value })
                    }
                    disabled={!!editingFlag}
                  >
                    <option value="bolo">BOLO (Be On Lookout)</option>
                    <option value="wanted">Wanted</option>
                    <option value="stolen">Stolen Vehicle</option>
                    <option value="warrant">Active Warrant</option>
                    <option value="suspicious">Suspicious Activity</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2 text-white">
                    Priority
                  </label>
                  <select
                    className="mdt-input w-full"
                    value={boloForm.priority}
                    onChange={(e) =>
                      setBoloForm({ ...boloForm, priority: e.target.value })
                    }
                  >
                    <option value="low">Low Priority</option>
                    <option value="medium">Medium Priority</option>
                    <option value="high">High Priority</option>
                    <option value="critical">Critical Priority</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2 text-white">
                    Description
                  </label>
                  <textarea
                    className="mdt-input w-full h-24 resize-none"
                    placeholder="Enter detailed description of the flag..."
                    value={boloForm.description}
                    onChange={(e) =>
                      setBoloForm({ ...boloForm, description: e.target.value })
                    }
                  />
                </div>
              </div>

              <div className="modal-footer">
                <button
                  className="mdt-button mdt-button-secondary"
                  onClick={closeBoloModal}
                >
                  Cancel
                </button>
                <button
                  className={classNames(
                    "mdt-button mdt-button-primary",
                    !boloForm.description.trim()
                      ? "opacity-50 cursor-not-allowed"
                      : ""
                  )}
                  onClick={handleBoloSubmit}
                  disabled={!boloForm.description.trim()}
                >
                  {editingFlag ? "Update Flag" : "Add Flag"}
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    );
  }

  // List view
  return (
    <div className="h-full flex flex-col gap-4">
      {/* Search Section */}
      <div className="mdt-card p-4">
        <div className="flex items-center gap-4">
          <div className="relative flex-1">
            <i className="fas fa-search absolute left-3 top-1/2 transform -translate-y-1/2 text-primary-200"></i>
            <input
              type="text"
              className="mdt-input pl-10 w-full"
              placeholder="Search by plate, model, owner name..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              onKeyPress={(e) => e.key === "Enter" && handleSearch()}
            />
          </div>
          <button
            className="mdt-button mdt-button-primary flex items-center gap-2"
            onClick={handleSearch}
            disabled={loading}
          >
            {loading ? (
              <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
            ) : (
              <i className="fas fa-search"></i>
            )}
            Search
          </button>
        </div>
      </div>

      {/* Results */}
      <div className="mdt-card flex-1 flex flex-col">
        <div className="flex-1 overflow-auto custom-scrollbar">
          {loading ? (
            <div className="flex items-center justify-center h-80">
              <div className="loading-spinner"></div>
            </div>
          ) : vehicles.length > 0 ? (
            <table className="mdt-table">
              <thead>
                <tr>
                  <th>Plate</th>
                  <th>Model</th>
                  <th>Owner</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {vehicles.map((vehicle) => {
                  const status = getVehicleStatus(vehicle);
                  return (
                    <tr key={vehicle.id}>
                      <td>
                        <span className="badge badge-outline">
                          {vehicle.plate}
                        </span>
                      </td>
                      <td className="text-white">{vehicle.model}</td>
                      <td>
                        <button
                          className="text-primary-400 hover:text-primary-300 transition-colors"
                          onClick={() => handleViewProfile(vehicle.citizenid)}
                        >
                          {vehicle.owner}
                        </button>
                      </td>
                      <td>
                        <span
                          className={classNames(
                            "badge text-white",
                            status.color
                          )}
                        >
                          {status.text}
                        </span>
                      </td>
                      <td>
                        <button
                          className="w-8 h-8 bg-primary-600 hover:bg-primary-700 rounded text-white transition-colors"
                          onClick={() => viewVehicle(vehicle.id)}
                        >
                          <i className="fas fa-eye"></i>
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          ) : hasSearched ? (
            <div className="empty-state h-80">
              <i className="fas fa-car empty-state-icon"></i>
              <h3 className="empty-state-title">No vehicles found</h3>
              <p className="empty-state-description">
                Try adjusting your search criteria
              </p>
            </div>
          ) : (
            <div className="empty-state h-80">
              <i className="fas fa-search empty-state-icon"></i>
              <h3 className="empty-state-title">Search for vehicles</h3>
              <p className="empty-state-description">
                Enter a plate number, model, or owner name to begin
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default VehiclesPage;

// web/src/lib/components/VehiclesPage.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { fetchNui } from '../utils/fetchNui';

  interface Vehicle {
    id: number;
    plate: string;
    model: string;
    owner: string;
    citizenid: string;
    state: number;
    locationStatus?: string;
    canViewLocation?: boolean;
    flags?: VehicleFlag[];
  }

  interface VehicleFlag {
    id: number;
    flag_type: string;
    description: string;
    reported_by: string;
    created_at: string;
    is_active?: boolean;
  }

  let {
    onViewProfile,
    navigationData
  }: {
    onViewProfile: (citizenid: string) => void;
    navigationData: any;
  } = $props();

  let searchQuery = $state('');
  let vehicles = $state<Vehicle[]>([]);
  let loading = $state(false);
  let expandedVehicleId = $state<number | null>(null);
  let expandedVehicle = $state<Vehicle | null>(null);
  let boloModalOpen = $state(false);
  let boloForm = $state({ flagType: 'bolo', description: '' });
  let debounceTimer: ReturnType<typeof setTimeout>;

  // Handle navigation from dashboard
  $effect(() => {
    const query = navigationData?.searchQuery || navigationData?.vehiclePlate;
    if (query) {
      searchQuery = query;
      searchVehicles(query, true);
    }
  });

  // Debounced search
  $effect(() => {
    if (debounceTimer) clearTimeout(debounceTimer);

    if (!searchQuery.trim()) {
      vehicles = [];
      return;
    }

    debounceTimer = setTimeout(() => {
      searchVehicles(searchQuery.trim(), false);
    }, 150);
  });

  async function searchVehicles(query: string, autoExpand: boolean) {
    if (!query.trim()) return;

    loading = true;
    expandedVehicleId = null;
    expandedVehicle = null;

    try {
      const results = await fetchNui<Vehicle[]>('searchVehicles', { query });
      vehicles = results || [];

      if (autoExpand && results && results.length > 0) {
        const exactMatch = results.find(v => v.plate.toUpperCase() === query.toUpperCase());
        const vehicleToExpand = exactMatch || (results.length === 1 ? results[0] : null);
        if (vehicleToExpand) {
          await toggleExpand(vehicleToExpand.id);
        }
      }
    } catch (error) {
      console.error('Error searching vehicles:', error);
      vehicles = [];
    } finally {
      loading = false;
    }
  }

  async function toggleExpand(vehicleId: number) {
    if (expandedVehicleId === vehicleId) {
      expandedVehicleId = null;
      expandedVehicle = null;
      return;
    }

    expandedVehicleId = vehicleId;
    try {
      const vehicle = await fetchNui<Vehicle>('getVehicle', { vehicleId });
      expandedVehicle = vehicle;
    } catch (error) {
      console.error('Error loading vehicle:', error);
    }
  }

  async function addFlag() {
    if (!expandedVehicle || !boloForm.description.trim()) return;

    try {
      const result = await fetchNui<{ success: boolean }>('addVehicleFlag', {
        vehicleId: expandedVehicle.id,
        plate: expandedVehicle.plate,
        flagType: boloForm.flagType,
        description: boloForm.description
      });

      if (result.success) {
        boloModalOpen = false;
        boloForm = { flagType: 'bolo', description: '' };
        await toggleExpand(expandedVehicle.id);
      }
    } catch (error) {
      console.error('Error adding flag:', error);
    }
  }

  async function removeFlag(flagId: number) {
    if (!expandedVehicle) return;

    try {
      const result = await fetchNui<{ success: boolean }>('removeVehicleFlag', {
        vehicleId: expandedVehicle.id,
        flagId
      });

      if (result.success) {
        await toggleExpand(expandedVehicle.id);
      }
    } catch (error) {
      console.error('Error removing flag:', error);
    }
  }

  function getStatusInfo(vehicle: Vehicle) {
    if (!vehicle.flags || vehicle.flags.length === 0) {
      return { text: 'CLEAR', color: 'text-mdt-text-subtle' };
    }

    const stolen = vehicle.flags.find(f => f.flag_type === 'stolen');
    if (stolen) return { text: 'STOLEN', color: 'text-red-400' };

    const warrant = vehicle.flags.find(f => f.flag_type === 'warrant');
    if (warrant) return { text: 'WARRANT', color: 'text-orange-400' };

    const bolo = vehicle.flags.find(f => f.flag_type === 'bolo');
    if (bolo) return { text: 'BOLO', color: 'text-yellow-400' };

    return { text: 'FLAG', color: 'text-blue-400' };
  }

  function getFlagColor(flagType: string) {
    const colors: Record<string, string> = {
      stolen: 'text-red-400',
      warrant: 'text-orange-400',
      bolo: 'text-yellow-400',
      suspicious: 'text-blue-400'
    };
    return colors[flagType] || 'text-mdt-text-muted';
  }
</script>

<div class="h-full flex flex-col">
  <!-- Search -->
  <div class="p-1 border-b border-mdt-border-subtle">
    <div class="relative">
      <i class="fas fa-search absolute left-2 top-1/2 -translate-y-1/2 text-mdt-text-subtle text-xs"></i>
      <input
        type="text"
        class="mdt-input w-full pl-8 pr-5 py-1 text-xs"
        placeholder="Search plate, model, or owner..."
        bind:value={searchQuery}
        style="border-radius: 2px;"
      />
      {#if searchQuery}
        <button
          class="absolute right-1.5 top-1/2 -translate-y-1/2 text-mdt-text-subtle hover:text-mdt-text"
          onclick={() => searchQuery = ''}
        >
          <i class="fas fa-times text-xs"></i>
        </button>
      {/if}
    </div>
  </div>

  <!-- Results -->
  <div class="flex-1 overflow-auto custom-scrollbar">
    {#if loading}
      <div class="flex items-center justify-center h-64">
        <div class="loading-spinner"></div>
      </div>
    {:else if !searchQuery.trim()}
      <div class="flex flex-col items-center justify-center h-64 text-mdt-text-subtle">
        <i class="fas fa-car text-2xl mb-2 opacity-40"></i>
        <span class="text-xs">Search for a vehicle</span>
      </div>
    {:else if vehicles.length === 0}
      <div class="flex flex-col items-center justify-center h-64 text-mdt-text-subtle">
        <i class="fas fa-search text-2xl mb-2 opacity-40"></i>
        <span class="text-xs">No results found</span>
      </div>
    {:else}
      <div>
        {#each vehicles as vehicle (vehicle.id)}
          {@const isExpanded = expandedVehicleId === vehicle.id}
          {@const status = getStatusInfo(vehicle)}
          <div class="border-b border-mdt-border-subtle last:border-b-0">
            <!-- Row -->
            <div
              class="flex items-center px-1 py-1 cursor-pointer transition-colors {isExpanded ? 'bg-mdt-bg-elevated' : 'hover:bg-mdt-bg-elevated/50'}"
              onclick={() => toggleExpand(vehicle.id)}
            >
              <div class="w-20 shrink-0">
                <span class="font-mono text-xs font-semibold text-mdt-text bg-mdt-bg-surface border border-mdt-border-subtle px-1 py-0.5" style="border-radius: 2px;">
                  {vehicle.plate}
                </span>
              </div>
              <span class="text-xs text-mdt-text-muted w-28 shrink-0 truncate">{vehicle.model}</span>
              <div class="flex-1 text-left truncate min-w-0">
                <button
                  class="text-xs text-primary-400 hover:text-primary-300"
                  onclick={(e) => { e.stopPropagation(); onViewProfile(vehicle.citizenid); }}
                >
                  {vehicle.owner}
                </button>
              </div>
              <span class="text-xs font-medium w-16 text-right {status.color}">{status.text}</span>
              <i class="fas fa-chevron-down text-xs text-mdt-text-subtle ml-1 transition-transform {isExpanded ? 'rotate-180' : ''}"></i>
            </div>

            <!-- Expanded -->
            {#if isExpanded && expandedVehicle}
              <div class="bg-mdt-bg px-1 py-1">
                <div class="flex gap-2">
                  <!-- Info -->
                  <div class="flex-1 space-y-1">
                    <div class="grid grid-cols-2 gap-x-2 gap-y-0.5">
                      <div class="flex justify-between">
                        <span class="text-xs text-mdt-text-subtle">Plate</span>
                        <span class="text-xs font-mono text-mdt-text">{expandedVehicle.plate}</span>
                      </div>
                      <div class="flex justify-between">
                        <span class="text-xs text-mdt-text-subtle">Model</span>
                        <span class="text-xs text-mdt-text">{expandedVehicle.model}</span>
                      </div>
                      <div class="flex justify-between">
                        <span class="text-xs text-mdt-text-subtle">Owner</span>
                        <button
                          class="text-xs text-primary-400 hover:text-primary-300"
                          onclick={() => onViewProfile(expandedVehicle!.citizenid)}
                        >
                          {expandedVehicle.owner}
                        </button>
                      </div>
                      {#if expandedVehicle.locationStatus}
                        <div class="flex justify-between">
                          <span class="text-xs text-mdt-text-subtle">Status</span>
                          <span class="text-xs text-mdt-text">{expandedVehicle.locationStatus}</span>
                        </div>
                      {/if}
                    </div>
                  </div>

                  <div class="w-px bg-mdt-border-subtle"></div>

                  <!-- Flags -->
                  <div class="w-56">
                    <div class="flex items-center justify-between mb-1">
                      <span class="text-xs text-mdt-text-subtle uppercase tracking-wider">
                        Flags {expandedVehicle.flags && expandedVehicle.flags.length > 0 ? `(${expandedVehicle.flags.length})` : ''}
                      </span>
                      <button
                        class="text-xs text-primary-400 hover:text-primary-300"
                        onclick={() => boloModalOpen = true}
                      >
                        + Add
                      </button>
                    </div>

                    {#if expandedVehicle.flags && expandedVehicle.flags.length > 0}
                      <div class="space-y-0.5 max-h-24 overflow-auto custom-scrollbar">
                        {#each expandedVehicle.flags as flag (flag.id)}
                          <div class="group flex items-start gap-1 py-0.5">
                            <span class="text-xs font-medium uppercase w-14 shrink-0 {getFlagColor(flag.flag_type)}">
                              {flag.flag_type}
                            </span>
                            <span class="text-xs text-mdt-text-muted flex-1 line-clamp-2">{flag.description}</span>
                            <button
                              class="opacity-0 group-hover:opacity-100 text-red-400 hover:text-red-300 transition-opacity"
                              onclick={() => removeFlag(flag.id)}
                            >
                              <i class="fas fa-times text-xs"></i>
                            </button>
                          </div>
                        {/each}
                      </div>
                    {:else}
                      <div class="text-xs text-mdt-text-subtle py-1 text-center">No active flags</div>
                    {/if}
                  </div>
                </div>
              </div>
            {/if}
          </div>
        {/each}
      </div>
    {/if}
  </div>
</div>

<!-- Add Flag Modal -->
{#if boloModalOpen}
<div class="modal-overlay" onclick={(e) => { if (e.target === e.currentTarget) boloModalOpen = false; }}>
  <div class="modal-container max-w-xs" onclick={(e) => e.stopPropagation()} style="border-radius: 2px;">
    <div class="modal-header" style="padding: 4px 6px;">
      <span class="text-xs font-medium text-mdt-text">Add Flag</span>
      <button onclick={() => boloModalOpen = false} class="text-mdt-text-subtle hover:text-mdt-text">
        <i class="fas fa-times text-xs"></i>
      </button>
    </div>
    <div class="modal-content space-y-1" style="padding: 4px 6px;">
      <div>
        <label class="block text-xs text-mdt-text-subtle mb-0.5">Type</label>
        <select class="mdt-input w-full text-xs py-0.5" bind:value={boloForm.flagType} style="border-radius: 2px;">
          <option value="bolo">BOLO</option>
          <option value="stolen">Stolen</option>
          <option value="warrant">Warrant</option>
          <option value="suspicious">Suspicious</option>
        </select>
      </div>
      <div>
        <label class="block text-xs text-mdt-text-subtle mb-0.5">Description</label>
        <textarea
          class="mdt-input w-full h-16 resize-none text-xs"
          placeholder="Enter description..."
          bind:value={boloForm.description}
          style="border-radius: 2px;"
        ></textarea>
      </div>
    </div>
    <div class="modal-footer" style="padding: 4px 6px;">
      <button class="mdt-button mdt-button-secondary text-xs py-0.5 px-1.5" onclick={() => boloModalOpen = false} style="border-radius: 2px;">Cancel</button>
      <button
        class="mdt-button mdt-button-primary text-xs py-0.5 px-1.5"
        class:opacity-50={!boloForm.description.trim()}
        onclick={addFlag}
        disabled={!boloForm.description.trim()}
        style="border-radius: 2px;"
      >
        Save
      </button>
    </div>
  </div>
</div>
{/if}
